version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: nexusqa-selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  chrome-1:
    image: selenium/node-chrome:4.18.1
    container_name: nexusqa-chrome-1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:7900"

  chrome-2:
    image: selenium/node-chrome:4.18.1
    container_name: nexusqa-chrome-2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7901:7900"

  firefox:
    image: selenium/node-firefox:4.18.1
    container_name: nexusqa-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  localstack:
    image: localstack/localstack:3.0
    container_name: nexusqa-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sns,cloudwatch,lambda
      - DEFAULT_REGION=us-east-1
      - DEBUG=0
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data: