apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: nexusqa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.0
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3,sns,cloudwatch,lambda"
            - name: DEFAULT_REGION
              value: "us-east-1"
            - name: DEBUG
              value: "0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: nexusqa
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      targetPort: 4566
  type: ClusterIP
