apiVersion: v1
kind: Namespace
metadata:
  name: nexusqa
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: nexusqa
spec:
  selector:
    app: selenium-hub
  ports:
    - name: hub
      port: 4444
      targetPort: 4444
    - name: publish
      port: 4442
      targetPort: 4442
    - name: subscribe
      port: 4443
      targetPort: 4443
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-external
  namespace: nexusqa
spec:
  selector:
    app: selenium-hub
  ports:
    - port: 4444
      targetPort: 4444
      nodePort: 30444
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nexusqa-service
  namespace: nexusqa
spec:
  selector:
    app: nexusqa
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer